### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by djhedges** [factrylabs/untimely-grafana-panel#13]
You have an image on medium.com queries as an example but the image is too blurry/downsized to read.  Would you mind updating?
https://medium.com/factry/introducing-the-untimely-grafana-panel-7d1ea61e2e3a

I've tried a few queries of my own with elapsed_duration_ms as the "reference" and voltage but all I get is a flat line.  Grafana seems to require a time column in the queries I wonder if that value is being graphed instead of the voltage.  I'm using Timescale/Postgres for the data source.

**Comment by HogeBlekker** [comment]
Hi! Sorry, did not see this come in.

The images on the medium article can be clicked to expand them and view at a larger resolution.

Please open a separate issue if you still have trouble with postgres. We have only tested InfluxDB with this panel.
